cardlib.lua
=> Fixed fatal Ddude error

cardlib.lua
Fixing things, adding things, my apologies
=> Giant erraneous commit

cardlib.lua, cardpacks.lua
=> Minor Errata, Added in Mariochocolatemilk, Jimminus, Aceguy100

cardlib.lua
Fixed Bloodspilled, nerfed Guest, Fixed Lilly_s, Seranok-ArtV, Wi_Sh, Pancake Break, Fenrier, Crazyblox, Mariochocolatemilk, Nerfd lopous
=> Fixed drunkenness 

cardlib.lua
=> Melee Disc. Working

HalloweenLib.lua, cardlib.lua
I don't think I have your assertion in after fetching. I don't know why.
=> Reformatted Alt-Arts.

cardlib.lua
=> Fixed merge errors

cardlib.lua, cardpacks.lua
Added Tricky Magician on card packs
Added Cat Ears Maid
Added Mafia Grunt
=> Pull Request (plz)

cardlibrary/10.12.16.lua
=> Change SoulSearch

cardlibrary/ancientstirrings.lua
Also reverted a Dairing balance patch
=> Add missing Ancient Stirrings arts

cardlibrary/10.12.16.lua
=> Fixed Arts

cardlibrary/10.12.16.lua, cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua
Cards are: ChosenCoast, Deadly Dicey Duo, Defaultio, Ghoost, Luck Warrior of Pure Gold, and MUTO2014.
mostly icon fixes
=> Fixed 6 Cards' arts

cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua
Fixed Morphic Goo, AII_DUCK, Infinite Frost, and Spooky Caverns
=> Card decal Fixes #2

cardlibrary/baselibrary.lua
=> Fix destruction5033

cardlibrary/baselibrary.lua
Missing regular art fix
Slight Imagin buff
Fix Redrune Raider's art
=> Rework One4utwo4me

cardlibrary/10.12.16.lua, cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua
Changed ChaoticCommando's stats as how we intended it to be
Re-Re-Fixed Ghoost and Morphic Goo's icon cost.
=> Minor changes to 4 cards (ChaoticCommando, Ghoost, Morphic Goo)

cardlibrary/baselibrary.lua
"Cast this card for free. At the end of this turn, lose 5 **white** icons. This effect causes negative icons."
=> Edited BrokenBone's effect description (neutral -> white)

cardlibrary/ancientstirrings.lua
The bio is now "He certainly is."
Happy?
=> Changed the bio on Cotton Candy Lion

cardlibrary/10.12.16.lua
If your really need a requirement, at least mention it in the effect's description.
=> Removed Requirement on xiVirtual's effect

cardlibrary/baselibrary.lua
Originally showed Saprasam's art
=> Fixed ID for Kmansong2 art

cardlibrary/10.12.16.lua
=> Fixed ID for Razikai's Exploration art

cardlibrary/baselibrary.lua
=> Fixed Robot (being able to generate icons)

cardlibrary/10.12.16.lua
https://www.roblox.com/library/918807176/Regular-TalkShow
=> Changed Regular_Talkshow's art

packs.lua
=> Fix Summer Salt pack.

cardlibrary/baselibrary.lua
=> Rewrote effect descriptions on Plushies

cardlibrary/baselibrary.lua
And one more pull request for this
=> Fix Builderman art.

cardlibrary/10.12.16.lua
=> Change some arts

cardlibrary/baselibrary.lua
I also putted Pixellus on the "hero" archetype
=> Fix Jimminus and Pixellus (both) arts

cardlibrary/baselibrary.lua
Here we go, I guess this must work right?
=> Fix LeetWizard effect putting the wrong art.

cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua
Helperbot's art has been incorrect for a while; the yellow icons and the white icons were in the wrong places. Blitzwolfer edited the card image.
=> Updated Helperbot's art

cardlibrary/baselibrary.lua
=> Fix CorgiParade only triggering OnDeath

packs.lua
EDIT: DON'T ACCEPT THIS UNTIL FURTHER NOTICE. CARD ART IS BEING REWORKED.
=> Added Fate_Sealed in the packs.

cardlibrary/10.12.16.lua
https://www.roblox.com/library/997944529/Lord-of-Auctions
=> Added Lord of Auctions

cardlibrary/10.12.16.lua
HE'S DONE IT, MYR FINALL DID HIS ART!
=> Fix Shard Master art.

cardlibrary/baselibrary.lua
DrWeasel, you fooled me, how dare ya.
=> Fix Nova Action description from 1 to 2

cardlibrary/baselibrary.lua
=> Fix Overseer General generating 2 green icons.

cardlibrary/baselibrary.lua
=> Filthypranks requested by Soul

cardlibrary/baselibrary.lua
"When this card Attacks, increase your lifepoints by 500." -> "Whenever this card attacks, you gain 500 Life."
=> Edited Inventor1116's effect description

cardlibrary/10.12.16.lua
https://www.roblox.com/library/1055575844/Superkicker2005
Basically added the cost to the original image.
=> Image Change for Superkicker2005

cardlibrary/baselibrary.lua
Cards Affected:
*PixelPistol
*Tomfl
*Exine
*BadBreadMaker
*GamesBloxx
*ChiefJustus
*OzzyPig
*Hop_Lee (Hopelesssly)
*Bincent
*Flufflefunz
*ShockingRobux
*Froot Ninja
*Zolerus
*IlIll (Barcode)
*Visleaf
*Medic Kit
*KnightDude
=> Rewritten several effect descriptions for cards

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1076071154/how-inconvenient
=> How_inconvenient

cardlibrary/baselibrary.lua
Because the old one is blurry as heck.
https://www.roblox.com/library/1137002780/Alkalola
=> Updated Alkalola's Card Art

cardlibrary/baselibrary.lua
=> Fixed Witch's True Brew

cardlibrary/10.12.16.lua, cardlibrary/baselibrary.lua
=> Fix wrong art of both green cards

cardlibrary/baselibrary.lua
Cards affected:
- Biostream
- Nexx
- Keeler1
- DIY Biggerhead
- Rockybow
- Ultoris Tenebrae
- Fave
- Frozen Phoenix
- Korblox Archer
- Korblox General
- Korblox Defender
- Korblox Shaman
- Korblox Deathknight
=> Rewritting several effect descriptions of cards.

cardlibrary/10.12.16.lua
Jesus christ do not let me near this code
=> Actually fixed SoulSearch

cardlibrary/baselibrary.lua
https://www.roblox.com/library/1187815470/Epic-Sauce
=> Replaced Epic Sauce's art

cardlibrary/10.12.16.lua
Apparently Kitten has a cost: one red icon. I made it cost no icons in order to correspond to the arts we have for the Kitten.
=> Kitten now doesn't cost any icons

cardlibrary/baselibrary.lua
https://www.roblox.com/library/897237736/GrandMeeboidTotemSummerAlt
=> Fixed Grand Meeboid Totem's alt art

cardlibrary/baselibrary.lua
Specified the effect a little bit more :0
=> Changed Plushie Unicorn's description

cardlibrary/10.12.16.lua
https://www.roblox.com/library/1221117313/ChaseThePsycho
=> ChaseThePsycho

cardlibrary/baselibrary.lua
By the request of theawesomist19 himself (peach_tea)
https://www.roblox.com/library/1209530021/peach-tea
=> Theawesomist19 -> Peach_tea

cardlibrary/10.12.16.lua, packs.lua
=> Add FourXIV

cardlibrary/ancientstirrings.lua
https://www.roblox.com/library/1237614790/huh
=> Fixed Morphic Goo's art

cardlibrary/ancientstirrings.lua
Also Buffed Cotton Candy Lion a little bit.
=> Part 2 of Crimbus Alt Arts

cardlibrary/ancientstirrings.lua
=> Revert "Part 2 of Crimbus Alt Arts" because brown goofed

cardlibrary/10.12.16.lua, cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua, packs.lua
Knuckles & Knuckles in Knuckles of Knuckles Featuring Knuckles From The Knuckles May Chuckle Series
=> Christmas Megadump & Silver_Semtexagon & Knuckles

cardlibrary/baselibrary.lua
to prevent us from getting under review
=> Fix Bio of entangling lights

cardlibrary/baselibrary.lua
I've noticed that Builderman's image in the code is a bit blurry, so I decided to fix that.
https://www.roblox.com/library/1266655937/Builderman
=> Fix Builderman's art - Builderman's art is now higher quality

cardlibrary/10.12.16.lua
hopefully it will do the effect properly after this.
=> Fix test dummy

cardlibrary/10.12.16.lua
=> ExtolYT configuring

cardlibrary/baselibrary.lua
https://www.roblox.com/library/1286602394/Korblox-Deathspeaker
do not merge if roblox denies image
=> Updated Korblox Deathspeaker Art

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1299508892/MesouricPhantom976
=> MesouricPhantom976

cardlibrary/baselibrary.lua
WWWWR -> WWWR cost
https://www.roblox.com/library/1303976830/Noobrae
=> Ultoris NOOBrae Buff

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1328298822/ThatGrimGuy
=> ThatGrimGuy

cardlibrary/baselibrary.lua
=> Pixellus Nerf

cardlibrary/baselibrary.lua
=> Ninja Kitty change

cardlibrary/baselibrary.lua
2xG -> 1xG cost
https://www.roblox.com/library/1346604876/Awful-Good-1G
=> Awful Good buff

cardlibrary/baselibrary.lua
WRBBB -> WBBB
https://www.roblox.com/library/1352072418/TheEnderCorp
=> TheEnderCorp Buff

cardlibrary/10.12.16.lua
https://www.roblox.com/library/1357349192/Exotic-Murtic-One-Charge-New
=> Exotic Murtic 1-Charge image change

cardlibrary/baselibrary.lua
Now only draws a card lol no genning 1 blue for u
=> AsrielMemer nerf

packs.lua
Added
- Bigtank_s
- Graalgamer
- Pilgrim
- Western Bandit
=> Added some yellow commons to Exine

cardlibrary/10.12.16.lua
=> Fix B550 effect

cardlibrary/baselibrary.lua
Tweety the Twitter Bird now sets your Life to 1000 OnSummon, rather than at the end of that turn.
=> Tweety the Twitter Bird buff

cardlibrary/10.12.16.lua
https://www.roblox.com/library/1372169759/darklord
=> Darklord1506 Buff

cardlibrary/baselibrary.lua
1. Cow - increase the health of a target fighter by 1.
2. Cow god - increase the health of all allied fighters by 1.
=> Cow Update

cardlibrary/baselibrary.lua
https://www.roblox.com/library/1375039481/derptasticdevil
=> derptasticdevil buff

cardlibrary/baselibrary.lua
=> Forestfire Butterflies fix

cardlibrary/baselibrary.lua
=> Witch's True Brew

cardlibrary/baselibrary.lua
=> DominatedLegacy buff

cardlibrary/baselibrary.lua
1. Lilman is no longer hit by his own aoe bread effect.
=> Lilmanofsalem Buff

cardlibrary/baselibrary.lua
1. Fixed arts so they are accurate to names/costs
2. Fixed typos in effects.
NOTE Bloxikin Horde didn't get fixed because its art got bounced :(
=> Card Error Fixes

cardlibrary/ancientstirrings.lua
Effect changed to onattack, not onattackend.
=> Pyramid Head Buff

cardlibrary/10.12.16.lua
=> test dummy stuff.png

cardlibrary/baselibrary.lua
6 blue icons -> **7 blue icons**
https://www.roblox.com/library/1446541685/Krocostar
=> Krocostar Nerf

cardlibrary/baselibrary.lua
andgssgbajgka
hladjhqadhnlhm;a
adhkah ap
=> Gusmanak fix

cardlibrary/ancientstirrings.lua
=> Unplumbed Lead buff

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1474056814/ThePestilentOne
Note: Graalgamer isn't in the revel packs apparently
=> ThePestilentOne

cardlibrary/ancientstirrings.lua
=> Ancient Stirrings bio rework

cardlibrary/baselibrary.lua
=> Valletta Buff

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1483291247/Creeperkiller510 -- Accept this when this image is accepted. If not, DO NOT ACCEPT IT.
Also: Shaylan007 and Indoorsnowball do not appear in the Vital packs for some reason?
=> Creeperkiller510

cardlibrary/baselibrary.lua
Removed Hero Archetype from Pixellus
=> Fixed Pixellus

cardlibrary/10.12.16.lua
Supposedly Vanjohnson breaks the game when it attacks and dies.
OnAttackEnd -> OnAttack
=> Vanjohnson fix

cardlibrary/baselibrary.lua
Increased effect cost (12k -> 14k)
=> Inceptiontime Nerf

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1754304822/MyCutenesskills
=> MyCutenesskills

cardlibrary/10.12.16.lua, packs.lua
https://www.roblox.com/library/1882355203/UncUncorruptedFinal
=> Unc, Uncorrupted

cardlibrary/baselibrary.lua
https://www.roblox.com/library/1950414129/ROBLOX
=> ROBLOX Image Higher Quality

cardlibrary/ancientstirrings.lua
https://www.roblox.com/library/2039538152/Summer-Hallow-2018
=> Hallow, the Sugarlord Alt

cardlibrary/baselibrary.lua
Made effect name "Barcode" so you can search it up easily on the deckbuilder's search bar
Friend Request Spammer now has a new art (https://www.roblox.com/library/2084782054/Friend-Request-Spammer-New) and costs 2 white icons.
=> Barcode + Friend Request Spammer

packs.lua
Also added Pikachukiller101 to the Yellow Revel packs (for some reason it wasn't in it)
=> Exine Pack Rework - Booster Edition

cardlibrary/10.12.16.lua, cardlibrary/ancientstirrings.lua, cardlibrary/baselibrary.lua
- Connoisseur
- KurosakiDXenos
=> blitzchanges#3

cardlibrary/20.11.18.lua
=> made majormattias an uncommon 500/500

cardlibrary/20.11.18.lua
berfing clonetrooper, makes its stats less insane but removes the lock, makes the card flow better
=> clonetrooper change

cardlibrary/20.11.18.lua
changed apog and happy clown for cycle consistency purposes
=> cycle consistancy
